### ISSUE TITLE
issue when running dm_analysis_stretch

### ISSUE THREAD

**Issue by gcojoc** [RI-imaging/DryMass#24] opened 2018-12-03 14:54 UTC
I got the following error when applying dm_analysis_stretch 
![error stretch](https://user-images.githubusercontent.com/34100125/49381014-493d6600-f713-11e8-9302-885595cd9c2d.JPG)

the am_analysis_sphere performed without error, but seems that there were issues too:

![error sphere](https://user-images.githubusercontent.com/34100125/49381169-9a4d5a00-f713-11e8-9f5a-b620c4a546e1.JPG)

**Comment by paulmueller** [comment] 2018-12-03 17:40
I get a similar error in ``dm_analyze_stretch``:
``IndexError: index -1457 is out of bounds for axis 1 with size 160``

The second issue (``dm_analyze_sphere``) is caused by the background image "SID PHA bg.tif", which appears to have extreme phase values. How did you record the background image?

**Comment by gcojoc** [comment] 2018-12-04 08:37
Update done. Do you still get the error after update?

**Comment by paulmueller** [comment] 2018-12-04 10:19
Without the background correction with "SID PHA bg.tif", qpstretch runs through just fine.

**Comment by gcojoc** [comment] 2018-12-04 14:44
> The second issue (dm_analyze_sphere) is caused by the background image "SID PHA bg.tif", which appears to have extreme phase values. How did you record the background image?


 Figured out the issue. In short, the imaged that is used for background correction was wrongly saved.

**Comment by paulmueller** [comment] 2018-12-04 14:52
ok, please let me know whether you still get the IndexError in dm_analyze_stretch.

**Comment by gcojoc** [comment] 2018-12-04 14:58
No, I do not get the index error when the background image is not used.

**Comment by paulmueller** [comment] 2018-12-04 14:59
ok good, closing this one.

**Closed by paulmueller** 2018-12-04 14:59 UTC
